name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
      - name: Install and build
        env:
          BUILD_SUBDIR: '/${{ github.event.repository.name }}/'
        run: |
          npm ci
          npx quasar build
          cp dist/spa/index.html dist/spa/404.html
      - name: Setup GH Pages
        uses: actions/configure-pages@v3
      - name: Upload GH Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/spa/'
      - name: Deploy GH Pages
        uses: actions/deploy-pages@v1
